### STAGE 1: Build ###
FROM node:16-alpine as build
WORKDIR /usr/src/app
ARG dir=eui-sdk-v1/

COPY ${dir}package.json ${dir}package-lock.json ./
RUN npm install
COPY ${dir}. .
RUN npm run build

### STAGE 2: Run ###
FROM nginx:1.17.1-alpine
COPY nginx.conf /etc/nginx/nginx.conf
COPY --from=build /usr/src/app/target/package /usr/share/nginx/html

EXPOSE 80