### STAGE 1: Build ###
FROM amazoncorretto:8-alpine-jdk AS build
WORKDIR /workspace/app

COPY springboot-api/pom.xml .
COPY springboot-api/src src/

RUN apk update && apk add maven && mvn install -DskipTests
RUN mkdir -p target/dependency && (cd target/dependency; jar -xf ../*.jar)


### STAGE 2: Run ###
FROM amazoncorretto:8-alpine-jre
VOLUME /tmp

ARG DEPENDENCY=/workspace/app/target/dependency

COPY --from=build ${DEPENDENCY}/BOOT-INF/lib /app/lib
COPY --from=build ${DEPENDENCY}/META-INF /app/META-INF
COPY --from=build ${DEPENDENCY}/BOOT-INF/classes /app

EXPOSE 8080
ENTRYPOINT ["java","-cp","app:app/lib/*","com.ericsson.graduates.projecte3.RetrospectiveToolApplication"]